id: P443C4941
initial_creation_type: input
source_metadata:
  title: Gheraṇḍasaṃhitā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Yoga
  data entry: Peter Thomi
  contribution to GRETIL: Peter Thomi
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:01:23.205876'
last_modified_at: '2022-03-09T15:01:23.205892'
